# Surf 3.2.1
# contact QQ:2682173972
# for help with this plugin

#Messages to send the player when they try to place illegal blocks
IllegalBlock-Place:
  Enabled: true
  Bedrock: '&6&l[&b&lSurf&6&l]&6 &6This block is not allowed'
  Barrier: '&6&l[&b&lSurf&6&l]&6 &6This block is not allowed'
  End_Portal_Frame: '&6&l[&b&lSurf&6&l]&6 &6This block is not allowed'
  Mob_Spawner: '&6&l[&b&lSurf&6&l]&6 &6This block is not allowed'
#ChunkBan skull limit tile entity limit and prevent message
ChunkBan:
  Enabled: true
  Prevent-Message: '&6&l[&b&lSurf&6&l]&6 &6ChunkBan has been disabled due to an exploit (^:'
  TileEntity-Max: 500
  Skull-Max: 100
#Nether top and bottom layers
Nether:
  Enabled: false
  Top-Layer: 127
  Top-message: '&6&l[&b&lSurf&6&l]&6 &6The nether top has been disabled due to lag'
  Bottom-Layer: 0
  Bottom-message: '&6&l[&b&lSurf&6&l]&6 &6The nether bottom has been disabled due to lag'
  top-bottom-do-damage: false
#Message to send to the server when a player first joins
#Use {Player} as a place holder for the players name
FirstJoin:
  Enabled: false
  Message: '&6[&bSurf&6] &c{Player}&6 has joined the &bYour&3Server &6for the first time'
#Elytra/redstone disable TPS values keep in mind this is a double so it can be like 13.2255
#Set 0 to disable 
#Elytra:
#  #the speed limit is 3 by default u can change it to what you want
#  SpeedLimit: 3
#  #enable / disable damage when going over the speed limit
#  EnableDamage: true
#  #change the amount of damage taken when going over the speed limit
#  DamageAmount: 15
#  #the tps that elytras gets completely disabled at
#  #you can turn this off by setting it to 1 basically
#  Disable-TPS: 17
#  #disable elytra fall damage ? set to false to enable fall damage when landing
#  EnableNoFallDamage: true
#  #enable taking off elytras when people go over the speed limit set to false to disable
#  EnableTakingOffElytra: false
#  #the message it sends to a player when they reach the elytra speed limit
#  SpeedLimitReached-message: "&6&l[&b&lSurf&6&l]&6 You are going to fast slow down"
#  #the message it sends to opped players when a player reaches the elytra speed limit
#  #you can turn this on or off by setting it to true or false
#  EnableOpMessages: true
#  SpeeedLimitReached-ops: "&6&l[&b&lSurf&6&l]&6 Player {name} is going to fast with an elytra"
#  #This will patch future clients packet elytra fly witch can be used to bypass most elytra speed limit plugins and make the elytra not lose any durability
#  PacketElytraFly-Enabled: true
#  #Sends a message to the player when they try to use PacketElytraFly
#  SendMessage: true
#  Message: "&6&l[&b&lSurf&6&l]&6&6 PacketElytraFly is currently disabled due to it causing tons of lag"
#Misc config shit
#Message to send when a player tries to use a 32k or strength 255
IllegalDamage:
  Message: "&6&l[&b&lSurf&6&l]&6&6 How did you even get a 32k out to begin with"
#Player attempts to use or drink an illegal potion or use an illegal tipped arrow
IllegalPotion:
  Message: "&6&l[&b&lSurf&6&l]&6&6 Sorry those are patched"
#Message to send the player when they use an elytra in low tps use {tps} to get the elytra disable tps
ElytraLowTPS:
  Message: "&6&l[&b&lSurf&6&l]&6 &6Elytras are disabled if the tps is below&r&c {tps}"
UnbookBan:
  Message: "&6&l[&b&lSurf&6&l]&6&6 You have been unbookbanned"
#Message for /discord use & for colors
#make sure to add the permission l2x9core.command.discord
Discord: "&6[&bSurf&6] Join us on discord at &chttp://discord.com"
#Ammount of vehicles allowed in a chunk
Minecart-per-chunk:
  limit: 500
#AntiIllegal check toggles
#Only enable ChunkLoad of you have a massive problem with illegals on your server
Antiillegal:
  Block-Place-Enabled: false
  ChunkLoad-Enabled: false
  HopperTransfer-Enabled: true
  InventoryClose-Enabled: true
  InventoryOpen-Enabled: true
  PlayerHotbarMove-Enabled: true
  ItemPickup: true
  Delete-Stacked-Items: true
  Check-Illegal-Damage: true
  Illegal-Items-List:
    - "BEDROCK"
    - "REPEATING_COMMAND_BLOCK"
    - "COMMAND_BLOCK_MINECART"
    - "CHAIN_COMMAND_BLOCK"
    - "COMMAND_BLOCK"
    - "END_PORTAL_FRAME"
    - "KNOWLEDGE_BOOK"
    - "SPAWNER"
    - "END_PORTAL"
    - "NETHER_PORTAL"
    - "END_PORTAL_FRAME"
    - "STRUCTURE_BLOCK"
    - "STRUCTURE_VOID"
#water / lava flowing disable tps this is useful on new servers with lots of block physics updates that cause lag
#Set -1 to disable
BlockPhysics-disable-tps: 15
#This is to prevent people from crashing / lagging the server by spam opening chest and other containers
#ChestLagFix:
#  MaxOpensPerSecond: 64
#  KickMessage: "&6&l[&b&lSurf&6&l]&6&c [AntiChestLag]&r&6 You have lost connection to the server"
#  RemoveUnicodeBooks: false
#These are the connection messages for when a player joins / leaves
#Use & for colours and %player% as a placeholder for the players name
Connection:
  Player-Join-Message: "&7[&a+&7] &8%player%"
  Player-Leave-Message: "&7[&c-&7] &8%player%"
