name: Surf
version: 3.2.3
main: org.surf.Main
authors: [ 254n_m, Leeewith3Es, Dreeam ]
description:  ${project.description}
website: https://breeze.asia
api-version: 1.18
softdepend:
  - SalC1Dupe
commands:
  surf:
    description: The main command of Surf.