name: Surf
version: 3.1.0
main: org.surf.Main
authors: [ 254n_m, Leeewith3Es, Dreeam ]
description:  ${project.description}
website: https://breeze.asia
softdepend:
  - SalC1Dupe
commands:
  surf:
    description: The main command of Surf.
  discord:
    description: Get the Discord link of the server.