name: SurfPatch
version: 3.1.0
main: org.surf.Main
authors: [ 254n_m, Leeewith3Es, Dreeam ]
description:  ${project.description}
softdepend:
  - SalC1Dupe
commands:
  surf:
    description: main command of this plugin
  discord:
    description: get discord link
