name: SurfPatch
version: 3.0.12
main: asia.breeze.surf.Main
authors: [ 254n_m, Leeewith3Es, Dreeam ]
description:  fix exploits and remove illegal items for anarchy servers
softdepend:
  - SalC1Dupe
commands:
  surf:
    description: main command of this plugin
  discord:
    description: get discord link
